shell = "zsh"

apply = ["defer"]

[templates]
defer = "{{ hooks | get: \"pre\" | nl }}{% for file in files %}zsh-defer -a -t0.01 source \"{{ file }}\"\n{% endfor %}{{ hooks | get: \"post\" | nl }}"
defer0 = "{{ hooks | get: \"pre\" | nl }}{% for file in files %}zsh-defer -a source \"{{ file }}\"\n{% endfor %}{{ hooks | get: \"post\" | nl }}"

[plugins]

####################
# eager
####################

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]
profiles = ["eager"]

[plugins.pure]
github = "sindresorhus/pure"
use = ["async.zsh", "pure.zsh"]
apply = ["fpath", "source"]
profiles = ["eager"]
hooks.post = """
autoload -Uz colors && colors
autoload -U promptinit && promptinit
zstyle :prompt:pure:path color 027
prompt pure
"""

[plugins.lazy]
local = "~/.config/zsh"
use = ["lazy.zsh"]
profiles = ["eager"]

####################
# lazy
####################

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
dir = "src"
apply = ["fpath"]
profiles = ["lazy"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
profiles = ["lazy"]

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'
profiles = ["lazy"]

[plugins.mise]
inline = """
if command -v mise &>/dev/null; then
    eval "$(mise activate zsh)"
    export MISE_NODE_DEFAULT_PACKAGES_FILE="$XDG_CONFIG_HOME/mise/default-npm-packages"
    export MISE_PYTHON_DEFAULT_PACKAGES_FILE="$XDG_CONFIG_HOME/mise/default-python-packages"
fi
"""
profiles = ["lazy"]

[plugins.compinit]
inline = """
autoload -Uz compinit
autoload -U bashcompinit
zsh-defer -a -t0.01 compinit -d "$XDG_STATE_HOME/zcompdump"
zsh-defer -a -t0.01 bashcompinit
"""
profiles = ["lazy"]

[plugins.terraform]
inline = """
if [ -x "$HOME/.local/share/mise/shims/terraform" ]; then
    zsh-defer -a -t0.02 complete -o nospace -C "$XDG_DATA_HOME/mise/shims/terraform" terraform
fi
"""
profiles = ["lazy"]

[plugins.finalize]
inline = """
# disable autocorrect in kiro and vscode terminal
autoload -Uz add-zsh-hook
disable_correction_if_needed() {
  if [[ "$TERM_PROGRAM" == "kiro" || "$TERM_PROGRAM" == "vscode" ]]; then
    setopt nocorrect
    # disable this hook after first run
    add-zsh-hook -d precmd disable_correction_if_needed
    unfunction disable_correction_if_needed
  fi
}
add-zsh-hook -Uz precmd disable_correction_if_needed

# Unset source function
unfunction source &>/dev/null
"""
profiles = ["lazy"]
