[settings]
# experimental = true
disable_backends = ["asdf"]

[settings.npm]
package_manager = "pnpm"

[tools]
firebase = "latest"
gemini-cli = "latest"
node = { version = "24", postinstall = "corepack enable && corepack prepare pnpm@latest --activate" }
"npm:aws-cdk" = "latest"
"npm:forever" = "latest"
terraform = "latest"

# required by mise autocompletion
usage = "latest"
