[settings]
# experimental = true
disable_backends = ["asdf"]

[tools]
firebase = "latest"
gemini-cli = "latest"
node = ["24", "22"]
"npm:aws-cdk" = "latest"
terraform = "latest"

# required by mise autocompletion
usage = "latest"
